In [25]:
# Dependencies
import pandas as pd
import numpy as np

In [26]:
# Store filepath in a variable
Poverty_Data = "Data/Poverty_Data.csv"
Poverty_Education_Data = "Data/Poverty_Education_Data.csv"
Income_Data = "Data/Income.csv"

In [27]:
Poverty_Data_df = pd.read_csv(Poverty_Data, encoding="ISO-8859-1", skiprows=[1], low_memory=False)
Poverty_Education_Data_df = pd.read_csv(Poverty_Education_Data, encoding="ISO-8859-1", skiprows=[1], low_memory=False)
Income_Data_df = pd.read_csv(Income_Data, encoding="ISO-8859-1", skiprows=[1], low_memory=False)

In [28]:
#Poverty_Education_Data_df.head()

In [29]:
Poverty_Data_df['GEO.display-label'] = Poverty_Data_df['GEO.display-label'].astype(str).str[-5:]
Poverty_Education_Data_df['GEO.display-label'] = Poverty_Education_Data_df['GEO.display-label'].astype(str).str[-5:]
Income_Data_df['GEO.display-label'] = Income_Data_df['GEO.display-label'].astype(str).str[-5:]

In [30]:
#Poverty_Education_Data_df.head()

In [31]:
del Poverty_Data_df['GEO.id']
del Poverty_Data_df['GEO.id2']
Poverty_Data_df.rename(columns={'GEO.display-label':'Zip Code'}, inplace=True)

del Poverty_Education_Data_df['GEO.id']
del Poverty_Education_Data_df['GEO.id2']
Poverty_Education_Data_df.rename(columns={'GEO.display-label':'Zip Code'}, inplace=True)

del Income_Data_df['GEO.id']
del Income_Data_df['GEO.id2']
Income_Data_df.rename(columns={'GEO.display-label':'Zip Code'}, inplace=True)

In [32]:
Income_Data_df.head()

,Zip Code,HC01_EST_VC02,HC01_MOE_VC02,HC02_EST_VC02,HC02_MOE_VC02,HC03_EST_VC02,HC03_MOE_VC02,HC01_EST_VC03,HC01_MOE_VC03,HC02_EST_VC03,...,HC02_EST_VC34,HC02_MOE_VC34,HC03_EST_VC34,HC03_MOE_VC34,HC01_EST_VC35,HC01_MOE_VC35,HC02_EST_VC35,HC02_MOE_VC35,HC03_EST_VC35,HC03_MOE_VC35
0,00601,5818,249,5818,249,18970,2094,2551,259,43.8,...,99.6,0.3,7046,776,59,47,0.3,0.3,6239,3904
1,00602,12719,374,12719,374,24179,1772,6863,382,54.0,...,93.7,1.1,8520,558,1603,373,4.1,1.0,16229,5909
2,00603,19009,503,19009,503,27627,2135,9212,450,48.5,...,97.5,0.7,10746,831,508,230,1.0,0.5,21970,11344
3,00606,1959,154,1959,154,16739,1970,1082,167,55.2,...,99.8,0.3,5971,710,12,22,0.2,0.3,-,**
4,00610,9120,375,9120,375,25085,1468,5103,374,56.0,...,97.3,0.9,9174,556,570,213,2.1,0.8,12710,3457